---
name: Python Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1
        with:
          path: packer-builder
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install flake8 pylint
      - name: flake8
        run: |
          flake8 packer_builder/
      - name: pylint
        run: |
          pylint packer_builder/
      - name: Install Packer
        env:
          PACKER_VERSION: 1.4.3
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin
          echo "Packer Version: $(packer --version)"
      - name: Generate Packer Templates
        run: |
          python -m packer_builder generate-templates --outputdir ~/projects/packer
